### ISSUE TITLE
Lab Report 3 Feedback

### ISSUE THREAD

**Issue by syptic** [khottinger/cse15-lab-reports#3]
**Streamlining `ssh` Configuration**

Here is your feedback for Lab Report 3 - Streamlining `ssh` Configuration:

- [x] Show your `.ssh/config` file, and how you edited it (with VScode, another program, etc)
- [x] Show the `ssh` command logging you into your account using just the alias you chose.
- [ ] Show an `scp` command copying a file to your account using just the alias you chose.
  - Yo did this w and w/o the alias but that defeats the purpose. 

Additional comments from your grader:
Rerun step 3 with only the alias command and for a file which doesn't exist in the ieng6 server.

--------

If you don't have all the checkmarks above, fix the issues described, and then submit a [regrade request on Gradescope](https://help.gradescope.com/article/8hchz9h8wh-student-regrade-request). Use this template for your regrade request:

- Link to this issue
- Link to your published lab report page

**Comment by khottinger** [comment]
I went ahead and re-ran step 3, I realized I forgot to add ":~/" add the end of my alias, but it has been fixed!
